#!/bin/zsh
# Made-up in the style of .xsession. Requires a file like
# /usr/share/wayland-sessions/wsession.desktop
# with contents (~ must be expanded):
# [Desktop Entry]
# Name=wsession shell script
# Exec=~/.wsession
# Type=Application

export PATH=~/.local/bin:$PATH

export GDK_BACKEND=wayland
export GTK_THEME=Adwaita:dark
# make qt behave
export QT_QPA_PLATFORM=wayland QT_QPA_PLATFORMTHEME=qt5ct
export QT_AUTO_SCREEN_SCALE_FACTOR=1 QT_ENABLE_HIGHDPI_SCALING=1
export MOZ_ENABLE_WAYLAND=1

export XDG_CURRENT_DESKTOP=sway
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
sway&; WM_PID=$!

# Apps that live in the tray.
blueman-applet&
keepassxc&
nm-applet&
strawberry&
syncthing -no-browser&

if [ -e ~/.wsession.local ]; then
  source ~/.wsession.local
fi

wait $WM_PID
