$font = Monospace

background {
  path = screenshot
  blur_passes = 5
}

input-field {
  size = 5%, 5%
  halign = center
  valign = center

  rounding = 15
  outline_thickness = 5
  font_family = $font

  inner_color = rgba(33333333)
  outer_color = rgba(888888dd)
  check_color = rgba(ff7900ee) rgba(306ac0ee) 315deg
  fail_color = rgba(ff6633ee) rgba(ff0066ee) 45deg
  font_color = rgb(ffffff)

  placeholder_text = password
  check_text =
  fail_text = WRONG
  fade_on_empty = false
  hide_input = true
}

label {
  position = 0, -400
  halign = center
  valign = top

  text = $TIME
  font_size = 110
  font_family = $font
}

label {
  position = 180, -5
  halign = center
  valign = center

  text = $LAYOUT[en,ar]
  font_size = 24
  onclick = hyprctl switchxkblayout all next
}
