#!/usr/bin/python3

from random import choice
from os import listdir, path, system

WALLPAPER_DIR = path.expanduser('~/pictures/wallpaper/mix')


def main():
  wallpapers = [w for w in listdir(WALLPAPER_DIR) if not w.startswith(".")]
  chosen_one = path.join(WALLPAPER_DIR, choice(wallpapers))
  system('feh --bg-fill "%s"' % chosen_one)


if __name__ == '__main__':
  main()

