# alacritty can't configure an emoji font here. workaround:
# ~/.config/fontconfig/conf.d/99-alacritty-emoji.conf
# <?xml version="1.0" encoding="UTF-8"?>
# <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
# 
# <!-- Alacritty doesn't support an explicit emoji font. -->
# <fontconfig>
#   <match>
#     <test name="prgname">
#       <string>alacritty</string>
#     </test>
#     <edit name="family" mode="prepend" binding="weak">
#       <string>Blobmoji</string>
#     </edit>
#   </match>
# </fontconfig>

[window]
opacity = 0.7
decorations = "none"

[font]
size = 10.0

[font.bold]
family = "Inconsolata"

[font.italic]
family = "Inconsolata"

[font.normal]
family = "Inconsolata"

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[colors.normal]
black = "0x2e3436"
blue = "0x3465a4"
cyan = "0x06989a"
green = "0x4e9a06"
magenta = "0x75507b"
red = "0xcc0000"
white = "0xd3d7cf"
yellow = "0xc4a000"

[colors.bright]
black = "0x555753"
blue = "0x729fcf"
cyan = "0x34e2e2"
green = "0x8ae234"
magenta = "0xad7fa8"
red = "0xef2929"
white = "0xeeeeec"
yellow = "0xfce94f"
